lang: en
project:
  type: book
  output-dir: docs
  resources: resources
execute:
  freeze: auto
book:
  title: Data Analysis Journeys
  subtitle: ''
  author:
  - orcid: 0000-0002-4191-5245
    name:
      family: Bartlett
      given: James
  - orcid: 0000-0002-5688-9537
    name:
      family: Toivo
      given: Wilhelmiina
  doi: ''
  license: CC-BY
  description: Data skills tasks to practice wrangling, visualising, and analysing data.
  cover-image: images/logos/DAJ_logo.png
  image: images/logos/DAJ_logo.png
  favicon: images/logos/DAJ_logo.png
  cookie-consent: false
  google-analytics: 'G-6NP3MF25W3'
  page-navigation: true
  search: true
  sidebar:
    title: ''
    logo: ''
    search: true
    contents: ''
    style: floating
    background: light
    foreground: dark
    border: true
    alignment: left
    collapse-level: 3
    pinned: true
    header: ''
    footer: ''
  margin-header: ''
  page-footer: CC-BY-4.0 (2025) Bartlett & Toivo
  chapters:
  - index.qmd
  - part: "Wrangling"
    chapters:
      - Bartlett-wrangle.qmd
  - part: "Analysis"
    chapters:
      - Evans-analysis.qmd
  appendices:
  - references.qmd
bibliography: include/book.bib
csl: include/apa.csl
format:
  html:
    theme:
      light:
      - flatly
      - include/light.scss
      dark:
      - darkly
      - include/dark.scss
    css:
    - https://use.fontawesome.com/releases/v5.13.0/css/all.css
    - include/booktem.css
    - include/webex.css
    - include/glossary.css
    - include/style.css
    df-print: kable
    code-link: true
    code-fold: false
    code-line-numbers: true
    code-overflow: wrap
    code-copy: hover
    highlight-style: a11y
    mainfont: ''
    monofont: ''
    include-after-body:
    - include/webex.js
    - include/script.js
